forms/products.py
from flask_wtf import FlaskForm

from wtforms.fields import StringField, SubmitField, DecimalField
from wtforms.validators import DataRequired, URL


class ProductForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description')
    price = DecimalField('Price', validators=[DataRequired()])
    picture_url = StringField('Picture URL')
    submit = SubmitField('Create')

blueprints/basket_api.py
from flask import Blueprint, render_template, redirect
from flask_login import current_user, login_required

from data import db_session
from data.products import Product
from data.users import User

basket = Blueprint('basket', __name__)


@basket.route('/add_to_basket/<int:product_id>')
@login_required
def add_to_basket(product_id):
    db_sess = db_session.create_session()
    prod = db_sess.query(Product).filter(Product.id == product_id).first()
    user = db_sess.query(User).filter(User.id == current_user.id).first()
    user.products.append(prod)
    db_sess.commit()
    return redirect('/')


@basket.route('/view_basket')
@login_required
def view_basket():
    total_price = sum([prod.price_cents for prod in current_user.products]) / 100
    return render_template('basket.html', products=current_user.products, total_price=total_price)


@basket.route('/delete_from_basket/<int:product_id>')
@login_required
def delete_from_basket(product_id):
    db_sess = db_session.create_session()
    prod = db_sess.query(Product).filter(Product.id == product_id).first()
    user = db_sess.query(User).filter(User.id == current_user.id).first()
    user.products.remove(prod)
    db_sess.commit()
    return redirect('/view_basket')

blueprints/products_api.py
from flask import Blueprint, abort, render_template, redirect, url_for, request
from flask_login import current_user

from data import db_session
from forms.products import ProductForm
from data.products import Product

products = Blueprint('products', __name__)


@products.route('/')
def index():
    db_sess = db_session.create_session()
    q = request.args.get('q', '')
    if q:
        all_products = db_sess.query(Product).filter(
            (Product.name.like(f'%{q.lower()}%')) | (Product.name.like(f'%{q.upper()}%')) | (
                Product.name.like(f'%{q.capitalize()}%'))).all()
        if len(all_products) == 0:
            all_products = db_sess.query(Product).filter(
                (Product.description.like(f'%{q.lower()}%')) | (Product.description.like(f'%{q.upper()}%')) | (
                    Product.description.like(f'%{q.capitalize()}%'))).all()
            if len(all_products) == 0:
                all_products = 'Nothing was found'
        else:
            res = db_sess.query(Product).filter(
                (Product.description.like(f'%{q.lower()}%')) | (Product.description.like(f'%{q.upper()}%')) | (
                    Product.description.like(f'%{q.capitalize()}%'))).all()
            for prod in res:
                if prod in all_products:
                    res.remove(prod)
            if len(res) != 0:
                all_products += res
    else:
        all_products = db_sess.query(Product).all()
    sort_by = request.args.get('sort_by', '')
    if sort_by:
        if sort_by == 'Rank by highest price':
            all_products = sorted(all_products, key=lambda x: -x.price_cents)
        elif sort_by == 'Rank by lowest price':
            all_products = sorted(all_products, key=lambda x: x.price_cents)
    return render_template('products/show.html', products=all_products)


@products.route('/products_list')
def products_list():
    db_sess = db_session.create_session()
    all_products = db_sess.query(Product).all()
    return render_template('products/products.html', products=all_products)


@products.route('/<int:product_id>')
def details(product_id):
    db_sess = db_session.create_session()
    product = db_sess.query(Product).filter(Product.id == product_id).first()
    return render_template('products/details.html', product=product)


@products.route('/create', methods=['GET', 'POST'])
def create():
    if current_user.is_admin:
        form = ProductForm()
        if form.validate_on_submit():
            product = Product()
            product.name = form.name.data
            product.description = form.description.data
            product.price_cents = int(form.price.data * 100)
            product.picture_url = form.picture_url.data
            db_sess = db_session.create_session()
            db_sess.add(product)
            db_sess.commit()
            return redirect(url_for('.details', product_id=product.id))
        return render_template('products/new.html', form=form)
    return redirect('/')


@products.route('/<int:product_id>/edit', methods=['GET', 'POST'])
def edit(product_id):
    if current_user.is_admin:
        db_sess = db_session.create_session()
        product = db_sess.query(Product).filter(Product.id == product_id).first()
        form = ProductForm(obj=product, price=product.price_cents / 100)
        if form.validate_on_submit():
            product.name = form.name.data
            product.description = form.description.data
            product.price_cents = int(form.price.data * 100)
            product.picture_url = form.picture_url.data
            db_sess.commit()
            return redirect(url_for('.details', product_id=product.id))
        return render_template('products/edit.html', product=product, form=form)
    return redirect('/')


@products.route('/product_delete/<int:product_id>', methods=['GET', 'POST'])
def delete(product_id):
    if current_user.is_admin:
        db_sess = db_session.create_session()
        product = db_sess.query(Product).filter(Product.id == product_id).first()
        if not product:
            abort(404)
        product_name = product.name
        db_sess.delete(product)
        db_sess.commit()
        return render_template('products/deleted.html', product_name=product_name)
    return redirect('/')

templates/products/deleted.html
{% extends "base.html" %}
{% block title %} Product was deleted {% endblock %}

{% block content %}
  <div class="container">
    <h1> Product {{ product_name }} was deleted</h1>
    <hr />
    <a class="btn btn-primary" href="{{ url_for('products.index') }}">
      View all products
    </a>
  </div>
{% endblock %}

templates/products/details.html
{% extends "base.html" %}
{% block title %} {{ product.name }} {% endblock %}

{% block content %}
  <div class="container">
    <img src="{{ product.get_image() }}" width="270px" class="img-thumbnail" />
    <h1> {{ product.name }} </h1>
    <hr />
    <span> {{ product.description }} </span>
    <hr />
      <h4>{{ product.price_cents / 100}} $</h4>
    {% if current_user.is_authenticated %}
    <a class="btn btn-success" href="{{ url_for('basket.add_to_basket', product_id=product.id) }}">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus" viewBox="0 0 16 16">
  <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9V5.5z"/>
  <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
  </svg>
    </a>
    {% endif %}
    {% if current_user.is_admin %}
                    <a href="{{ url_for('products.delete', product_id=product.id) }}">
                        <button type="submit" class="btn btn-primary">Delete</button></a>
                    <a href="{{ url_for('products.edit', product_id=product.id) }}">
                        <button type="submit" class="btn btn-primary">Edit</button></a>
    {% endif %}
  </div>
{% endblock %}

templates/products/edit.html
{% extends "base.html" %}

{% block title %} Edit {{ product.name }} {% endblock %}

{% block content %}
  <div class="container">

    <form method="POST" action="{{ url_for('products.edit', product_id=product.id) }}">
      {{ form.hidden_tag() }}
    <p>
        {{ form.name.label }}*<br>
        {{ form.name(class="form-control") }}<br>
        {% for error in form.name.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.description.label }}<br>
        {{ form.description(class="form-control") }}<br>
        {% for error in form.description.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.price.label }}*<br>
        {{ form.price(class="form-control") }}<br>
        {% for error in form.price.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.picture_url.label }}<br>
        {{ form.picture_url(class="form-control") }}<br>
        {% for error in form.picture_url.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p><button type="submit" class="btn btn-primary">Edit</button></p>
    </form>

  </div>
{% endblock %}

templates/products/new.html
{% extends "base.html" %}

{% block title %} New Product {% endblock %}

{% block content %}
  <div class="container">

    <form method="POST" action="{{ url_for('products.create') }}">
      {{ form.hidden_tag() }}
    <p>
        {{ form.name.label }}*<br>
        {{ form.name(class="form-control") }}<br>
        {% for error in form.name.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.description.label }}<br>
        {{ form.description(class="form-control") }}<br>
        {% for error in form.description.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.price.label }}*<br>
        {{ form.price(class="form-control") }}<br>
        {% for error in form.price.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.picture_url.label }}<br>
        {{ form.picture_url(class="form-control") }}<br>
        {% for error in form.picture_url.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p><button type="submit" class="btn btn-primary">Create</button></p>
    </form>

  </div>
{% endblock %}

templates/products/products.html
{% extends "base.html" %}
{% block title %} All Products {% endblock %}

{% block content %}
  <div class="container">
      <a href="{{ url_for('products.create') }}" class="btn btn-secondary">Add new product</a>
      <hr />
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
              <th scope="col">Price</th>
              {% if current_user.is_authenticated %}
              <th scope="col">Actions</th>
              {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for product in products %}
            <tr>
              <th scope="row">
                <a href="{{ url_for('products.details', product_id=product.id) }}">
                    <img src="{{ product.get_image() }}" width="40px" class="img-thumbnail" />
                    {{ product.name }}
                </a>
              </th>
              <th scope="row">{{ product.description }}</th>
                <th scope="row">{{ product.price_cents / 100 }} $</th>
                <th scope="row">
                    {% if current_user.is_authenticated %}
                        <a class="btn btn-success" href="{{ url_for('products.index', product_id=product.id) }}">
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus" viewBox="0 0 16 16">
                      <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9V5.5z"/>
                      <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                      </svg>
                        </a>
                        {% endif %}
                    {% if current_user.is_admin %}
                    <a href="{{ url_for('products.delete', product_id=product.id) }}">
                        <button type="submit" class="btn btn-primary">Delete</button></a>
                    <a href="{{ url_for('products.edit', product_id=product.id) }}">
                        <button type="submit" class="btn btn-primary">Edit</button></a>
                {% endif %}
                </th>
            </tr>
        {% endfor %}
        </tbody>
    </table>

  </div>
{% endblock %}

templates/products/show.html
{% extends "base.html" %}
{% block title %} All Products {% endblock %}

{% block content %}

<form class="navbar-form navbar-left" method="GET">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Search" name="q" value="{{ request.args.get('q', '') }}">
    </div>
   <p><select name="sort_by">
    <option>Sort by</option>
    <option>Rank by lowest price</option>
    <option>Rank by highest price</option>
   </select>
    <button type="submit"  class="btn btn-primary">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
          <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
        </svg>Search</button>
  </form>

<div class="container">
    <div class="row">
        {% if products != 'Nothing was found' %}
      {% for product in products %}
        <div class="card mr-2" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">{{ product.name }}</h5>
                <h6>{{ product.price_cents / 100 }} $</h6>
            </div>
             <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <img src="{{ product.get_image() }}" width="250px" class="img-thumbnail" />
                </li>
            </ul>
            <div class="card-body">
              <a href="{{ url_for('products.details', product_id=product.id) }}" class="card-link btn btn-primary">
                View more
              </a>
                {% if current_user.is_authenticated %}
                    <a class="btn btn-success" href="{{ url_for('basket.add_to_basket', product_id=product.id) }}">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus" viewBox="0 0 16 16">
                  <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9V5.5z"/>
                  <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                  </svg>
                    </a>
                {% endif %}
            </div>
          </div>
      {% endfor %}
        {% else %}
        <h4>Nothing was found ;(</h4>
        {% endif %}

    </div>

  </div>
{% endblock %}