blueprints/basket_api.py
from flask import Blueprint, render_template, redirect
from flask_login import current_user, login_required

from data import db_session
from data.products import Product
from data.users import User

basket = Blueprint('basket', __name__)


@basket.route('/add_to_basket/<int:product_id>')
@login_required
def add_to_basket(product_id):
    db_sess = db_session.create_session()
    prod = db_sess.query(Product).filter(Product.id == product_id).first()
    user = db_sess.query(User).filter(User.id == current_user.id).first()
    user.products.append(prod)
    db_sess.commit()
    return redirect('/')


@basket.route('/view_basket')
@login_required
def view_basket():
    total_price = sum([prod.price_cents for prod in current_user.products]) / 100
    return render_template('basket.html', products=current_user.products, total_price=total_price)


@basket.route('/delete_from_basket/<int:product_id>')
@login_required
def delete_from_basket(product_id):
    db_sess = db_session.create_session()
    prod = db_sess.query(Product).filter(Product.id == product_id).first()
    user = db_sess.query(User).filter(User.id == current_user.id).first()
    user.products.remove(prod)
    db_sess.commit()
    return redirect('/view_basket')

blueprints/products_api.py
from flask import Blueprint, abort, render_template, redirect, url_for, request
from flask_login import current_user

from data import db_session
from forms.products import ProductForm
from data.products import Product

products = Blueprint('products', __name__)


@products.route('/')
def index():
    db_sess = db_session.create_session()
    q = request.args.get('q', '')
    if q:
        all_products = db_sess.query(Product).filter(
            (Product.name.like(f'%{q.lower()}%')) | (Product.name.like(f'%{q.upper()}%')) | (
                Product.name.like(f'%{q.capitalize()}%'))).all()
        if len(all_products) == 0:
            all_products = db_sess.query(Product).filter(
                (Product.description.like(f'%{q.lower()}%')) | (Product.description.like(f'%{q.upper()}%')) | (
                    Product.description.like(f'%{q.capitalize()}%'))).all()
            if len(all_products) == 0:
                all_products = 'Nothing was found'
        else:
            res = db_sess.query(Product).filter(
                (Product.description.like(f'%{q.lower()}%')) | (Product.description.like(f'%{q.upper()}%')) | (
                    Product.description.like(f'%{q.capitalize()}%'))).all()
            for prod in res:
                if prod in all_products:
                    res.remove(prod)
            if len(res) != 0:
                all_products += res
    else:
        all_products = db_sess.query(Product).all()
    sort_by = request.args.get('sort_by', '')
    if sort_by:
        if sort_by == 'Rank by highest price':
            all_products = sorted(all_products, key=lambda x: -x.price_cents)
        elif sort_by == 'Rank by lowest price':
            all_products = sorted(all_products, key=lambda x: x.price_cents)
    return render_template('products/show.html', products=all_products)


@products.route('/products_list')
def products_list():
    db_sess = db_session.create_session()
    all_products = db_sess.query(Product).all()
    return render_template('products/products.html', products=all_products)


@products.route('/<int:product_id>')
def details(product_id):
    db_sess = db_session.create_session()
    product = db_sess.query(Product).filter(Product.id == product_id).first()
    return render_template('products/details.html', product=product)


@products.route('/create', methods=['GET', 'POST'])
def create():
    if current_user.is_admin:
        form = ProductForm()
        if form.validate_on_submit():
            product = Product()
            product.name = form.name.data
            product.description = form.description.data
            product.price_cents = int(form.price.data * 100)
            product.picture_url = form.picture_url.data
            db_sess = db_session.create_session()
            db_sess.add(product)
            db_sess.commit()
            return redirect(url_for('.details', product_id=product.id))
        return render_template('products/new.html', form=form)
    return redirect('/')


@products.route('/<int:product_id>/edit', methods=['GET', 'POST'])
def edit(product_id):
    if current_user.is_admin:
        db_sess = db_session.create_session()
        product = db_sess.query(Product).filter(Product.id == product_id).first()
        form = ProductForm(obj=product, price=product.price_cents / 100)
        if form.validate_on_submit():
            product.name = form.name.data
            product.description = form.description.data
            product.price_cents = int(form.price.data * 100)
            product.picture_url = form.picture_url.data
            db_sess.commit()
            return redirect(url_for('.details', product_id=product.id))
        return render_template('products/edit.html', product=product, form=form)
    return redirect('/')


@products.route('/product_delete/<int:product_id>', methods=['GET', 'POST'])
def delete(product_id):
    if current_user.is_admin:
        db_sess = db_session.create_session()
        product = db_sess.query(Product).filter(Product.id == product_id).first()
        if not product:
            abort(404)
        product_name = product.name
        db_sess.delete(product)
        db_sess.commit()
        return render_template('products/deleted.html', product_name=product_name)
    return redirect('/')

blueprints/users_api.py
from flask import Blueprint, render_template, redirect
from flask_login import LoginManager, logout_user, login_required, current_user, login_user

from data import db_session
from data.users import User
from forms.users import EditForm, LoginForm, RegisterForm

users = Blueprint('users', __name__)
login_manager = LoginManager()


@login_manager.user_loader
def load_user(user_id):
    db_sess = db_session.create_session()
    return db_sess.query(User).get(user_id)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect("/")


@users.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = EditForm(obj=current_user)
    if form.validate_on_submit():
        db_sess = db_session.create_session()
        user = db_sess.query(User).filter(User.id == current_user.id).first()
        if not user.check_password(form.password.data):
            return render_template('users/edit.html', title='Profile',
                                   form=form,
                                   message="Wrong password")
        if form.new_password.data != form.new_password_again.data:
            return render_template('users/edit.html', title='Profile',
                                   form=form,
                                   message="Passwords don't match")
        if db_sess.query(User).filter(User.email == form.email.data).first() and form.email.data != user.email:
            return render_template('users/edit.html', title='Profile',
                                   form=form,
                                   message="User with this email already exists")
        user.name = form.name.data
        user.email = form.email.data
        user.address = form.address.data
        user.phone_number = form.phone_number.data
        if len(form.new_password.data) > 0:
            user.set_password(form.new_password.data)
        db_sess.commit()
        return render_template('users/edit.html', title='Profile', form=form, message="Profile was updated")
    return render_template('users/edit.html', title='Profile', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        db_sess = db_session.create_session()
        user = db_sess.query(User).filter(User.email == form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            return redirect("/")
        return render_template('users/login.html',
                               message="Wrong email or password",
                               form=form)
    return render_template('users/login.html', title='Authorization', form=form)


@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        if form.password.data != form.password_again.data:
            return render_template('users/register.html', title='Registration',
                                   form=form,
                                   message="Passwords don't match")
        db_sess = db_session.create_session()
        if db_sess.query(User).filter(User.email == form.email.data).first():
            return render_template('users/register.html', title='Registration',
                                   form=form,
                                   message="This user already exists")
        user = User()
        user.name = form.name.data
        user.email = form.email.data
        user.address = form.address.data
        user.phone_number = form.phone_number.data
        user.set_password(form.password.data)
        db_sess.add(user)
        db_sess.commit()
        return redirect('/login')
    return render_template('users/register.html', title='Registration', form=form)


@users.route('/users_list/<int:user_id>')
@login_required
def edit_user(user_id):
    db_sess = db_session.create_session()
    if current_user.is_admin:
        user = db_sess.query(User).filter(User.id == user_id).first()
        if user.is_admin:
            user.is_admin = False
        else:
            user.is_admin = True
        db_sess.commit()
        return redirect('/users_list')


@users.route('/users_list')
@login_required
def show_users():
    db_sess = db_session.create_session()
    all_users = db_sess.query(User).all()
    return render_template('users/users_list.html', users=all_users)


@users.route('/delete_user/<int:user_id>')
@login_required
def delete_user(user_id):
    if current_user.is_admin or user_id == current_user.id:
        db_sess = db_session.create_session()
        user = db_sess.query(User).filter(User.id == user_id).first()
        db_sess.delete(user)
        db_sess.commit()
    return redirect('/')

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %} | Juice Shop</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-light bg-light justify-content-between">
            <a href=" {{ url_for('products.index') }} " class="navbar-brand">Juice Shop</a>
            {% if current_user.is_authenticated %}
            <p>
                <a class="navbar-brand" href="/profile" ><u>{{ current_user.name }}</u></a>
            {% if current_user.is_admin %}
                <a class="navbar-brand" href="/products_list">All products</a>
                <a class="navbar-brand" href="/users_list">All users</a>
            {% endif %}
                <a class="btn btn-primary" href="{{ url_for('basket.view_basket') }}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg></a>
                <a href="{{ url_for('users.logout') }}" class="btn btn-secondary">Log out</a>
            </p>
            {% else %}
                <p>
                    <a class="btn btn-primary " href="/register">Sign Up</a>
                    <a class="btn btn-success" href="/login">Log in</a>
                </p>
            {% endif %}
        </nav>
        <div class="container mt-3">
            {% block content %}{% endblock %}
        </div>
    <br>
    <br>
    </body>
</html>

templates/basket.html
{% extends "base.html" %}
{% block title %} Basket {% endblock %}

{% block content %}
<div class="container">
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
             <th scope="col"> </th>
          </tr>
        </thead>
        <tbody>
          {% for product in products %}
            <tr>
              <th scope="row">
                <a href="{{ url_for('products.details', product_id=product.id) }}">
                    <img src="{{ product.get_image() }}" width="40px" class="img-thumbnail" />
                    {{ product.name }}
                </a>
              </th>
              <th scope="row">
                  {{ product.price_cents / 100 }} $
              </th>
                <th scope="row">
                    <a href="{{ url_for('buy', product_id=product.id) }}" class="btn btn-success">Buy</a>
                  <a class="btn btn-danger" href="{{ url_for('basket.delete_from_basket', product_id=product.id) }}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-dash" viewBox="0 0 16 16">
                  <path d="M6.5 7a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1h-4z"/>
                  <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                </svg>Remove</a>
                </th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <hr />
    <h5>Total Price: ${{ total_price }}</h5>
    <a href="{{ url_for('buy_all') }}" class="btn btn-success">Buy All</a>
  </div>
{% endblock %}

templates/buy.html
{% extends "base.html" %}
{% block title %} Basket {% endblock %}

{% block content %}
    <div class="row g-5">
      <div class="col-md-5 col-lg-4 order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-primary">Your cart</span>
          <span class="badge bg-primary rounded-pill">{{ count }}</span>
        </h4>
        <ul class="list-group mb-3">
          {% for product in products %}
            <li class="list-group-item d-flex justify-content-between lh-sm">
              <div>
                <h6 class="my-0">{{ product.name }}</h6>
              </div>
              <span class="text-muted">${{ product.price_cents / 100}}</span>
            </li>
          {% endfor %}
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>${{ total_price }}</strong>
          </li>
        </ul>



      </div>
      <div class="col-md-7 col-lg-8">
        <h4 class="mb-3">Billing address</h4>
        <form class="needs-validation" novalidate>
          <div class="row g-3">
            <div class="col-sm-6">
              <label for="firstName" class="form-label">First name</label>
              <input type="text" class="form-control" id="firstName" placeholder="" value="" required>
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-sm-6">
              <label for="lastName" class="form-label">Last name</label>
              <input type="text" class="form-control" id="lastName" placeholder="" value="" required>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>

            <div class="col-12">
              <label for="username" class="form-label">Username</label>
              <div class="input-group has-validation">
                <input type="text" class="form-control" id="username" placeholder="Username" required>
              <div class="invalid-feedback">
                  Your username is required.
                </div>
              </div>
            </div>

            <div class="col-12">
              <label for="email" class="form-label">Email <span class="text-muted">(Optional)</span></label>
              <input type="email" class="form-control" id="email" placeholder="you@example.com">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="col-12">
              <label for="address" class="form-label">Address</label>
              <input type="text" class="form-control" id="address" required>
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

            <div class="col-md-3">
              <label for="zip" class="form-label">Zip</label>
              <input type="text" class="form-control" id="zip" placeholder="" required>
              <div class="invalid-feedback">
                Zip code required.
              </div>
            </div>
          </div>

          <hr class="my-4">

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="save-info">
            <label class="form-check-label" for="save-info">Save this information for next time</label>
          </div>

          <hr class="my-4">

          <h4 class="mb-3">Payment</h4>

          <div class="row gy-3">
            <div class="col-md-6">
              <label for="cc-name" class="form-label">Name on card</label>
              <input type="text" class="form-control" id="cc-name" placeholder="" required>
              <small class="text-muted">Full name as displayed on card</small>
              <div class="invalid-feedback">
                Name on card is required
              </div>
            </div>

            <div class="col-md-6">
              <label for="cc-number" class="form-label">Credit card number</label>
              <input type="text" class="form-control" id="cc-number" placeholder="" required>
              <div class="invalid-feedback">
                Credit card number is required
              </div>
            </div>

            <div class="col-md-3">
              <label for="cc-expiration" class="form-label">Expiration</label>
              <input type="text" class="form-control" id="cc-expiration" placeholder="" required>
              <div class="invalid-feedback">
                Expiration date required
              </div>
            </div>

            <div class="col-md-3">
              <label for="cc-cvv" class="form-label">CVV</label>
              <input type="text" class="form-control" id="cc-cvv" placeholder="" required>
              <div class="invalid-feedback">
                Security code required
              </div>
            </div>
          </div>

          <hr class="my-4">

          <button class="w-100 btn btn-primary btn-lg" type="submit">Continue to checkout</button>
        </form>
      </div>
    </div>
  </main>

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>