forms/users.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField, BooleanField
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired


class RegisterForm(FlaskForm):
    email = EmailField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    password_again = PasswordField('Confirm password', validators=[DataRequired()])
    name = StringField('Name', validators=[DataRequired()])
    address = StringField('Address')
    phone_number = StringField('Phone number')
    submit = SubmitField('Submit')


class EditForm(FlaskForm):
    email = EmailField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    new_password = PasswordField('New password')
    new_password_again = PasswordField('Confirm new password')
    name = StringField('Name', validators=[DataRequired()])
    address = StringField('Address')
    phone_number = StringField('Phone number')
    submit = SubmitField('Submit')


class LoginForm(FlaskForm):
    email = EmailField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember me')
    submit = SubmitField('Login')

blueprints/users_api.py
from flask import Blueprint, render_template, redirect
from flask_login import LoginManager, logout_user, login_required, current_user, login_user

from data import db_session
from data.users import User
from forms.users import EditForm, LoginForm, RegisterForm

users = Blueprint('users', __name__)
login_manager = LoginManager()


@login_manager.user_loader
def load_user(user_id):
    db_sess = db_session.create_session()
    return db_sess.query(User).get(user_id)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect("/")


@users.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = EditForm(obj=current_user)
    if form.validate_on_submit():
        db_sess = db_session.create_session()
        user = db_sess.query(User).filter(User.id == current_user.id).first()
        if not user.check_password(form.password.data):
            return render_template('users/edit.html', title='Profile',
                                   form=form,
                                   message="Wrong password")
        if form.new_password.data != form.new_password_again.data:
            return render_template('users/edit.html', title='Profile',
                                   form=form,
                                   message="Passwords don't match")
        if db_sess.query(User).filter(User.email == form.email.data).first() and form.email.data != user.email:
            return render_template('users/edit.html', title='Profile',
                                   form=form,
                                   message="User with this email already exists")
        user.name = form.name.data
        user.email = form.email.data
        user.address = form.address.data
        user.phone_number = form.phone_number.data
        if len(form.new_password.data) > 0:
            user.set_password(form.new_password.data)
        db_sess.commit()
        return render_template('users/edit.html', title='Profile', form=form, message="Profile was updated")
    return render_template('users/edit.html', title='Profile', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        db_sess = db_session.create_session()
        user = db_sess.query(User).filter(User.email == form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            return redirect("/")
        return render_template('users/login.html',
                               message="Wrong email or password",
                               form=form)
    return render_template('users/login.html', title='Authorization', form=form)


@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        if form.password.data != form.password_again.data:
            return render_template('users/register.html', title='Registration',
                                   form=form,
                                   message="Passwords don't match")
        db_sess = db_session.create_session()
        if db_sess.query(User).filter(User.email == form.email.data).first():
            return render_template('users/register.html', title='Registration',
                                   form=form,
                                   message="This user already exists")
        user = User()
        user.name = form.name.data
        user.email = form.email.data
        user.address = form.address.data
        user.phone_number = form.phone_number.data
        user.set_password(form.password.data)
        db_sess.add(user)
        db_sess.commit()
        return redirect('/login')
    return render_template('users/register.html', title='Registration', form=form)


@users.route('/users_list/<int:user_id>')
@login_required
def edit_user(user_id):
    db_sess = db_session.create_session()
    if current_user.is_admin:
        user = db_sess.query(User).filter(User.id == user_id).first()
        if user.is_admin:
            user.is_admin = False
        else:
            user.is_admin = True
        db_sess.commit()
        return redirect('/users_list')


@users.route('/users_list')
@login_required
def show_users():
    db_sess = db_session.create_session()
    all_users = db_sess.query(User).all()
    return render_template('users/users_list.html', users=all_users)


@users.route('/delete_user/<int:user_id>')
@login_required
def delete_user(user_id):
    if current_user.is_admin or user_id == current_user.id:
        db_sess = db_session.create_session()
        user = db_sess.query(User).filter(User.id == user_id).first()
        db_sess.delete(user)
        db_sess.commit()
    return redirect('/')

templates/users/edit.html
{% extends "base.html" %}
{% block title %} Profile {% endblock %}

{% block content %}
<h1>Profile information</h1>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.email.label }}<br>
        {{ form.email(class="form-control", type="email") }}<br>
        {% for error in form.email.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.name.label }}<br>
        {{ form.name(class="form-control") }}<br>
        {% for error in form.name.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.phone_number.label }}<br>
        {{ form.phone_number(class="form-control") }}<br>
        {% for error in form.phone_number.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.address.label }}<br>
        {{ form.address(class="form-control") }}<br>
        {% for error in form.address.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.password.label }}<br>
        {{ form.password(class="form-control", type="password") }}<br>
        {% for error in form.password.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.new_password.label }}<br>
        {{ form.new_password(class="form-control", type="password") }}<br>
        {% for error in form.new_password.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.new_password_again.label }}<br>
        {{ form.new_password_again(class="form-control", type="password") }}<br>
        {% for error in form.new_password_again.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>{{ form.submit(type="submit", class="btn btn-primary") }}
    <a href="{{ url_for('users.logout') }}" class="btn btn-primary">Log out</a>
        {% if current_user.id != 1 %}
    <a href="{{ url_for('users.delete_user', user_id=current_user.id) }}" class="btn btn-danger">Delete account</a>
    {% endif %}
    </p>
    {{message}}
    <br>
</form>
{% endblock %}

templates/users/login.html
{% extends "base.html" %}
{% block title %} Login {% endblock %}
{% block content %}
    <h1>Log in</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}<br>
            {{ form.email(class="form-control", type="email") }}<br>
            {% for error in form.email.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(class="form-control", type="password") }}<br>
            {% for error in form.password.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit(type="submit", class="btn btn-primary") }}</p>
        <div>{{ message }}</div>
    </form>
{% endblock %}

templates/users/register.html
{% extends "base.html" %}
{% block title %} Sign Up {% endblock %}
{% block content %}
<h1>Sign Up</h1>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.email.label }} *<br>
        {{ form.email(class="form-control", type="email") }}<br>
        {% for error in form.email.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.name.label }} *<br>
        {{ form.name(class="form-control") }}<br>
        {% for error in form.name.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>

    <p>
        {{ form.phone_number.label }}<br>
        {{ form.phone_number(class="form-control") }}<br>
        {% for error in form.phone_number.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.address.label }}<br>
        {{ form.address(class="form-control") }}<br>
        {% for error in form.address.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.password.label }} *<br>
        {{ form.password(class="form-control", type="password") }}<br>
        {% for error in form.password.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.password_again.label }} *<br>
        {{ form.password_again(class="form-control", type="password") }}<br>
        {% for error in form.password_again.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>{{ form.submit(type="submit", class="btn btn-primary") }}</p>
    {{message}}
    <br>
</form>
{% endblock %}

templates/users/users_list.html
{% extends "base.html" %}
{% block title %} All Users {% endblock %}

{% block content %}
  <div class="container">
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Address</th>
            <th scope="col">Phone number</th>
              <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for user in users %}
            <tr>
              <th scope="row">
                    {{ user.name }}
              </th>
              <th scope="row">{{ user.email }}</th>
                <th scope="row">{{ user.address }}</th>
                <th scope="row">{{ user.phone_number }}</th>

                    <th scope="row"><a href="{{ url_for('users.delete_user', user_id=user.id) }}">
                        {% if user.id != 1 %}
                        <button type="submit" class="btn btn-primary">Delete</button></a>
                        {% if user.is_admin %}
                            <a href="{{ url_for('users.show_users', user_id=user.id) }}">
                            <button type="submit" class="btn btn-primary">Downgrade</button></a>
                        {% else %}
                            <a href="{{ url_for('users.edit_user', user_id=user.id) }}">
                            <button type="submit" class="btn btn-primary">Make admin</button></a>
                        {% endif %}
                        {% endif %}
                    </th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
  </div>
{% endblock %}